export const LOGIN_PAGE_REQUEST = 'LOGIN_PAGE_REQUEST';
export const LOGIN_PAGE_SUCCESS = 'LOGIN_PAGE_SUCCESS';
export const LOGIN_PAGE_FAILED = 'LOGIN_PAGE_FAILED';

export const LOGOUT_PAGE_REQUEST = 'LOGOUT_PAGE_REQUEST';
export const LOGOUT_PAGE_SUCCESS = 'LOGOUT_PAGE_SUCCESS';
export const LOGOUT_PAGE_FAILED = 'LOGOUT_PAGE_FAILED';