export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST'
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'
export const UPDATE_CART_FAIL = 'UPDATE_CART_FAIL'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'

export const CITY_LIST_REQUEST = 'CITY_LIST_REQUEST'
export const CITY_LIST_SUCCESS = 'CITY_LIST_SUCCESS'
export const CITY_LIST_FAIL = 'CITY_LIST_FAIL'

export const DEPARTMENT_LIST_REQUEST = 'DEPARTMENT_LIST_REQUEST'
export const DEPARTMENT_LIST_SUCCESS = 'DEPARTMENT_LIST_SUCCESS'
export const DEPARTMENT_LIST_FAIL = 'DEPARTMENT_LIST_FAIL'

export const CREATE_NEW_ORDER_REQUEST = 'CREATE_NEW_ORDER_REQUEST'
export const CREATE_NEW_ORDER_SUCCESS = 'CREATE_NEW_ORDER_SUCCESS'
export const CREATE_NEW_ORDER_FAIL = 'CREATE_NEW_ORDER_FAIL'
