export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST'
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'
export const UPDATE_CART_FAIL = 'UPDATE_CART_FAIL'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'