export const GET_CATALOG_PAGE_REQUEST = 'GET_CATALOG_PAGE_REQUEST'
export const GET_CATALOG_PAGE_SUCCESS = 'GET_CATALOG_PAGE_SUCCESS'
export const GET_CATALOG_PAGE_FAIL = 'GET_CATALOG_PAGE_FAIL'


export const GET_DETAILED_CATALOG_REQUEST = 'GET_DETAILED_CATALOG_REQUEST'
export const GET_DETAILED_CATALOG_SUCCESS = 'GET_DETAILED_CATALOG_SUCCESS'
export const GET_DETAILED_CATALOG_FAIL = 'GET_DETAILED_CATALOG_FAIL'