export const GET_NEW_ITEM_PAGE_REQUEST = 'GET_NEW_ITEM_PAGE_REQUEST'
export const GET_NEW_ITEM_PAGE_SUCCESS = 'GET_NEW_ITEM_PAGE_SUCCESS'
export const GET_NEW_ITEM_PAGE_FAIL = 'GET_NEW_ITEM_PAGE_FAIL'